In [ ]:
import numpy as np

In [3]:
# ---- Step 1: Define the vocabulary ----
vocab = ["I", "love", "cats"]
word_to_ix = {word: i for i, word in enumerate(vocab)}
word_to_ix


{'I': 0, 'love': 1, 'cats': 2}

In [4]:
# ---- Step 2: One-hot encoding ----
def one_hot(idx, size):
    vec = np.zeros(size)
    vec[idx] = 1.0
    return vec


In [5]:
# ---- Step 3: Initialize weights and hidden state ----
input_size = 3     # one-hot size
hidden_size = 2    # size of the RNN memory


In [8]:
# Weights (random small numbers)
W = np.random.randn(hidden_size, input_size) * 0.1
U = np.random.randn(hidden_size, hidden_size) * 0.1
b = np.zeros(hidden_size)

# Initial hidden state
h_prev = np.zeros(hidden_size)

W, U, b, h_prev

(array([[-0.04229369,  0.06272946,  0.02243791],
        [-0.09266698, -0.01642113,  0.11307286]]),
 array([[-0.02324619, -0.06041382],
        [-0.05441866, -0.05885374]]),
 array([0., 0.]),
 array([0., 0.]))

In [9]:


# ---- Step 4: Input sentence ----
sentence = ["I", "love", "cats"]

print("Step-by-step hidden states:\n")

for word in sentence:
    x = one_hot(word_to_ix[word], input_size)  # input vector
    h_t = np.tanh(np.dot(W, x) + np.dot(U, h_prev) + b)  # RNN update
    print(f"Word: {word:5}  | Hidden state: {h_t}")
    h_prev = h_t  # carry hidden state forward

Step-by-step hidden states:

Word: I      | Hidden state: [-0.04226849 -0.09240264]
Word: love   | Hidden state: [ 0.06918374 -0.00868247]
Word: cats   | Hidden state: [0.02135095 0.10937961]


In [10]:
# ---- Step 5: Final hidden state ----
print("\nFinal hidden state:", h_prev)
# This is the final hidden state after processing the entire sentence.
# It can be used for further tasks like classification or sequence generation.
# The hidden state captures the context of the input sequence.          


Final hidden state: [0.02135095 0.10937961]
